# Generated by Django 5.2.3 on 2025-07-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='foodItems',
            new_name='foodItem',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
